Fix withStatement wrapping for SQL and Python (#2051)
Because community sends all the language snippets to Visual Studio Code,
the inability to wrap in SQL means you can't wrap in Python either:

```
ValueError: No variable '0' in Snippet(name='withStatement', body='WITH $1 AS (\n\tSELECT $0\n)', description=None, phrases=['with'], insertion_scopes=['statement'], languages=['sql'], variables=[])
```